<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\helengine.shader\helengine.shader.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\helengine.shader\shaders\compilation\**\*.cs"
             Link="shaders\compilation\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
