namespace helengine {
    /// <summary>
    /// Applies split positional contact correction to body poses without changing kinetic velocities or solver impulses.
    /// </summary>
    sealed class HelPhysicsPenetrationCorrector3D {
        /// <summary>
        /// Stores overlap tolerated before positional correction begins.
        /// </summary>
        static readonly PhysicsScalar PenetrationSlop = PhysicsScalar.FromFloat(0.005f);

        /// <summary>
        /// Stores the fraction of penetration beyond slop removed by one correction pass.
        /// </summary>
        static readonly PhysicsScalar CorrectionFraction = PhysicsScalar.FromFloat(0.2f);

        /// <summary>
        /// Stores the largest separation distance one contact may request in one correction pass.
        /// </summary>
        static readonly PhysicsScalar MaximumCorrection = PhysicsScalar.FromFloat(0.2f);

        /// <summary>
        /// Corrects all prepared contact poses in deterministic order using their precomputed normal effective masses.
        /// </summary>
        /// <param name="bodies">Fixed body pool containing every prepared contact participant.</param>
        /// <param name="constraints">Constructor-owned solver constraints containing penetration and response data.</param>
        /// <param name="constraintCount">Number of leading prepared constraints to correct.</param>
        /// <exception cref="ArgumentNullException">Thrown when a required pool or constraint array is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="constraintCount"/> lies outside the fixed array.</exception>
        public void CorrectPenetration(
            HelPhysicsBodyPool3D bodies,
            HelPhysicsContactConstraint3D[] constraints,
            int constraintCount) {
            if (bodies == null) {
                throw new ArgumentNullException(nameof(bodies));
            } else if (constraints == null) {
                throw new ArgumentNullException(nameof(constraints));
            }

            if (constraintCount < 0 || constraintCount > constraints.Length) {
                throw new ArgumentOutOfRangeException(nameof(constraintCount), "Correction count must fit fixed constraint storage.");
            }

            for (int constraintIndex = 0; constraintIndex < constraintCount; constraintIndex++) {
                ref HelPhysicsContactConstraint3D constraint = ref constraints[constraintIndex];
                PhysicsScalar correctableDepth = constraint.PenetrationDepth - PenetrationSlop;
                if (correctableDepth <= PhysicsScalar.Zero || constraint.NormalEffectiveMass <= PhysicsScalar.Zero) {
                    continue;
                }

                PhysicsScalar correctionDistance = PhysicsScalar.Min(
                    correctableDepth * CorrectionFraction,
                    MaximumCorrection);
                PhysicsScalar positionalImpulseMagnitude = correctionDistance * constraint.NormalEffectiveMass;
                PhysicsVector3 positionalImpulse = constraint.Normal * positionalImpulseMagnitude;
                if (constraint.RespondsA) {
                    ref HelPhysicsBodyState3D bodyA = ref bodies.GetRequiredStateByIndex(constraint.BodyAIndex);
                    bodyA.Position -= positionalImpulse * constraint.InverseMassA;
                    PhysicsVector3 angularCorrectionA = -constraint.WorldInverseInertiaA.Transform(
                        PhysicsVector3.Cross(constraint.LeverArmA, positionalImpulse));
                    bodyA.Orientation = ApplyAngularCorrection(bodyA.Orientation, angularCorrectionA);
                }

                if (constraint.RespondsB) {
                    ref HelPhysicsBodyState3D bodyB = ref bodies.GetRequiredStateByIndex(constraint.BodyBIndex);
                    bodyB.Position += positionalImpulse * constraint.InverseMassB;
                    PhysicsVector3 angularCorrectionB = constraint.WorldInverseInertiaB.Transform(
                        PhysicsVector3.Cross(constraint.LeverArmB, positionalImpulse));
                    bodyB.Orientation = ApplyAngularCorrection(bodyB.Orientation, angularCorrectionB);
                }
            }
        }

        /// <summary>
        /// Applies one small world-space angular displacement to an orientation and normalizes the result.
        /// </summary>
        /// <param name="orientation">Current normalized body orientation.</param>
        /// <param name="angularCorrection">World-space angular displacement generated by a positional impulse.</param>
        /// <returns>Normalized orientation after the angular correction.</returns>
        static PhysicsQuaternion ApplyAngularCorrection(
            PhysicsQuaternion orientation,
            PhysicsVector3 angularCorrection) {
            PhysicsScalar half = PhysicsScalar.FromFloat(0.5f);
            PhysicsQuaternion corrected = new PhysicsQuaternion(
                orientation.X + (((angularCorrection.X * orientation.W) +
                    (angularCorrection.Y * orientation.Z) -
                    (angularCorrection.Z * orientation.Y)) * half),
                orientation.Y + ((-(angularCorrection.X * orientation.Z) +
                    (angularCorrection.Y * orientation.W) +
                    (angularCorrection.Z * orientation.X)) * half),
                orientation.Z + (((angularCorrection.X * orientation.Y) -
                    (angularCorrection.Y * orientation.X) +
                    (angularCorrection.Z * orientation.W)) * half),
                orientation.W - (((angularCorrection.X * orientation.X) +
                    (angularCorrection.Y * orientation.Y) +
                    (angularCorrection.Z * orientation.Z)) * half));
            return corrected.Normalized();
        }
    }
}
