using System.Diagnostics;
using System.Drawing.Imaging;
using System.Text.Json;
using helengine.media;
using SharpDX.Direct3D;
using SharpDX.Direct3D11;
namespace helengine.media.windows.tests;
/// <summary>Full audiovisual acceptance across aspect ratios, containers and standalone packaging.</summary>
public sealed class CompositionAcceptanceTests {
    /// <summary>Trusted installed codec executable; no production editorial filters are used.</summary>
    const string Ffmpeg="C:/env/ffmpeg-8.1.1-full_build-shared/bin/ffmpeg.exe";
    /// <summary>Expected published package outside all source checkouts.</summary>
    const string Package="C:/dev/helworks/builds/helengine/media-composition/packages/acceptance";
    /// <summary>Three formats and both containers preserve exact pre-encode timing and the known flash/impulse.</summary>
    [Theory] [InlineData(540,960,"mp4-h264-aac.v1","mp4")] [InlineData(960,540,"mp4-h264-aac.v1","mp4")] [InlineData(540,540,"mp4-h264-aac.v1","mp4")] [InlineData(540,960,"mov-prores4444-pcm.v1","mov")] [InlineData(960,540,"mov-prores4444-pcm.v1","mov")] [InlineData(540,540,"mov-prores4444-pcm.v1","mov")]
    public async Task FullCompositionKeepsAvSyncAcrossFormats(int width,int height,string profile,string extension) {
        var document=CompositionAcceptanceFixture.Create(width,height);Assert.Empty(CompositionValidator.Validate(document,WindowsMediaCapabilities.Describe()));using var device=new Device(DriverType.Warp,DeviceCreationFlags.BgraSupport);using var resolver=new WindowsMediaSourceResolver(CompositionAcceptanceFixture.Root,device);using var compositor=new DirectX11MediaCompositor(device,resolver);using var mixer=new CompositionAudioMixer(resolver);using var encoder=new FfmpegCompositionEncoder(Ffmpeg);using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(120));var exporter=new CompositionExporter(compositor,mixer,encoder,WindowsMediaCapabilities.Describe());
        var samples=mixer.Render(document,47992,16).Block.Samples.ToArray();Assert.InRange(samples[16],.74999f,.75001f);Assert.True(samples.Where((value,index)=>index%2==0).Select((value,index)=>new{value,index}).OrderByDescending(item=>Math.Abs(item.value)).First().index==8);
        using(var flash=compositor.Render(document,new(1,1),new(width,height))) {var rgba=flash.Surface.ReadRgba();Assert.InRange(rgba.Span[(4*width+4)*4],245,255);SavePng(flash,Path.Combine(CompositionAcceptanceFixture.Root,$"flash-{width}x{height}.png"));using var same=compositor.Render(document,new(1,1),new(width,height));Assert.Equal(rgba.ToArray(),same.Surface.ReadRgba().ToArray());}
        string output=Path.Combine(CompositionAcceptanceFixture.Root,$"acceptance-{width}x{height}.{extension}");var report=await exporter.ExportAsync(document,OutputProfile.Resolve(profile,width,height),output,timeout.Token);Assert.Equal(144,report.FrameCount);Assert.Equal(288000,report.SampleCount);Assert.True(report.HasAudio);Assert.InRange(report.AudioPeak,.74999,.75001);
        byte[] decoded=await Diagnostic(["-v","error","-ss","1","-i",output,"-frames:v","1","-f","rawvideo","-pix_fmt","rgba","pipe:1"]);Assert.Equal(width*height*4,decoded.Length);Assert.InRange(decoded[(4*width+4)*4],240,255);
        if(extension=="mov") {byte[] pcm=await Diagnostic(["-v","error","-i",output,"-map","0:a:0","-f","f32le","-ac","2","-ar","48000","pipe:1"]);Assert.Equal(288000*8,pcm.Length);Assert.InRange(BitConverter.ToSingle(pcm,48000*8),.74999f,.75001f);}else {byte[] pcm=await Diagnostic(["-v","error","-i",output,"-map","0:a:0","-f","f32le","-ac","2","-ar","48000","pipe:1"]);int frames=pcm.Length/8;Assert.InRange(frames,288000,289024);int peak=Enumerable.Range(47500,1000).OrderByDescending(index=>Math.Abs(BitConverter.ToSingle(pcm,index*8))).First();Assert.InRange(peak,48000-2000,48000+2000);}
    }
    /// <summary>A clean published package resolves shaders, native decoder and PCM without source-tree fallback.</summary>
    [Fact] public async Task NativePackageWorksOutsideCheckout() {
        string cli=Path.Combine(Package,"helengine.vfx.cli.dll");Assert.True(File.Exists(cli),"Standalone composition package is missing.");Assert.True(File.Exists(Path.Combine(Package,"helengine.video.ffmpeg.dll")));Assert.True(File.Exists(Path.Combine(Package,"media/shaders/MediaCrossfade.hlsl")));var document=CompositionAcceptanceFixture.Create(128,128);string input=Path.Combine(CompositionAcceptanceFixture.Root,"package-composition.json");await File.WriteAllTextAsync(input,CompositionJson.Serialize(document));string output=Path.Combine(CompositionAcceptanceFixture.Root,"package-render.mp4");var result=await Run("dotnet",[cli,"composition","render","--input",input,"--assets-root",CompositionAcceptanceFixture.Root,"--out",output,"--profile","mp4-h264-aac.v1","--ffmpeg",Ffmpeg,"--warp","true"],Package);using var report=JsonDocument.Parse(System.Text.Encoding.UTF8.GetString(result));Assert.Equal(144,report.RootElement.GetProperty("frame_count").GetInt64());Assert.Equal(288000,report.RootElement.GetProperty("sample_count").GetInt64());Assert.True(File.Exists(output));
    }
    /// <summary>Both real cancellation and a failed encoder leave no final output or receipt.</summary>
    [Fact] public async Task EncoderFailureAndCancelLeaveNoPublishedOutput() {
        var document=CompositionAcceptanceFixture.Create(32,32);using var device=new Device(DriverType.Warp,DeviceCreationFlags.BgraSupport);using var resolver=new WindowsMediaSourceResolver(CompositionAcceptanceFixture.Root,device);using var compositor=new DirectX11MediaCompositor(device,resolver);using var mixer=new CompositionAudioMixer(resolver);string failed=Path.Combine(CompositionAcceptanceFixture.Root,"failed-"+Guid.NewGuid().ToString("N")+".mp4");using var fake=new FailingCompositionEncoder();await Assert.ThrowsAsync<IOException>(()=>new CompositionExporter(compositor,mixer,fake,WindowsMediaCapabilities.Describe()).ExportAsync(document,OutputProfile.Resolve("mp4-h264-aac.v1",32,32),failed,CancellationToken.None));Assert.False(File.Exists(failed));Assert.False(File.Exists(failed+".report.json"));Assert.Empty(Directory.GetFiles(CompositionAcceptanceFixture.Root,Path.GetFileName(failed)+".*.partial*"));
        string canceled=Path.Combine(CompositionAcceptanceFixture.Root,"canceled-"+Guid.NewGuid().ToString("N")+".mp4");using var encoder=new FfmpegCompositionEncoder(Ffmpeg);using var cancellation=new CancellationTokenSource(50);await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>new CompositionExporter(compositor,mixer,encoder,WindowsMediaCapabilities.Describe()).ExportAsync(document,OutputProfile.Resolve("mp4-h264-aac.v1",32,32),canceled,cancellation.Token));Assert.False(File.Exists(canceled));Assert.False(File.Exists(canceled+".report.json"));Assert.Empty(Directory.GetFiles(CompositionAcceptanceFixture.Root,Path.GetFileName(canceled)+".*.partial*"));
    }
    /// <summary>Runs fixture diagnostics, separate from the encoding-only production argument path.</summary>
    static Task<byte[]> Diagnostic(string[] args)=>Run(Ffmpeg,args,CompositionAcceptanceFixture.Root);
    /// <summary>Captures bounded synthetic fixture streams without shell interpolation.</summary>
    static async Task<byte[]> Run(string executable,string[] args,string directory) {var start=new ProcessStartInfo(executable){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=directory,RedirectStandardOutput=true,RedirectStandardError=true};foreach(string arg in args)start.ArgumentList.Add(arg);using var process=Process.Start(start);using var memory=new MemoryStream();var output=process.StandardOutput.BaseStream.CopyToAsync(memory);var error=process.StandardError.ReadToEndAsync();using var cancellation=new CancellationTokenSource(TimeSpan.FromSeconds(120));using var registration=cancellation.Token.Register(()=>{try{if(!process.HasExited)process.Kill(true);}catch(InvalidOperationException){}});await Task.WhenAll(output,process.WaitForExitAsync(cancellation.Token));Assert.True(process.ExitCode==0,await error);return memory.ToArray();}
    /// <summary>Writes a diagnostics image of owned rendered content, not a screenshot of the user's computer.</summary>
    static void SavePng(MediaVideoFrame frame,string output) {byte[] rgba=frame.Surface.ReadRgba().ToArray();using var bitmap=new System.Drawing.Bitmap(frame.Surface.Width,frame.Surface.Height,PixelFormat.Format32bppArgb);var data=bitmap.LockBits(new(0,0,bitmap.Width,bitmap.Height),ImageLockMode.WriteOnly,PixelFormat.Format32bppArgb);try {for(int index=0;index<rgba.Length;index+=4){byte red=rgba[index];rgba[index]=rgba[index+2];rgba[index+2]=red;}for(int row=0;row<bitmap.Height;row++)System.Runtime.InteropServices.Marshal.Copy(rgba,row*bitmap.Width*4,IntPtr.Add(data.Scan0,row*data.Stride),bitmap.Width*4);}finally{bitmap.UnlockBits(data);}bitmap.Save(output,ImageFormat.Png);}
}
