using System.Text.Json;
namespace helengine.vfx.cli.tests;
/// <summary>Checks composition subcommand routing and controlled JSON failures without GPU allocation.</summary>
public sealed class CompositionCliTests {
    /// <summary>The catalog command produces the exact versioned capability document.</summary>
    [Fact] public void CapabilitiesAreVersionedJson() {using var json=JsonDocument.Parse(CompositionCliRunner.CapabilitiesJson());Assert.Equal("helengine.media.capabilities.v1",json.RootElement.GetProperty("schema").GetString());Assert.Contains(json.RootElement.GetProperty("effects").EnumerateArray(),effect=>effect.GetProperty("id").GetString()=="crossfade");}
    /// <summary>The catalog lists the built-in scene arrangements with their regions and roles, so planners can choose them.</summary>
    [Fact] public void CapabilitiesListSceneArrangements() {using var json=JsonDocument.Parse(CompositionCliRunner.CapabilitiesJson());var arrangements=json.RootElement.GetProperty("arrangements").EnumerateArray().ToList();Assert.Equal(["full","stack","split","take_with_graphic","take_behind_graphic","graphic_only"],arrangements.Select(item=>item.GetProperty("id").GetString()));var stack=arrangements[1];Assert.False(string.IsNullOrWhiteSpace(stack.GetProperty("description").GetString()));Assert.Equal(["top:graphic","main:picture"],stack.GetProperty("regions").EnumerateArray().Select(region=>region.GetProperty("name").GetString()+":"+region.GetProperty("role").GetString()));}
    /// <summary>The catalog advertises overlay timelines: the format, bindable slot kinds, compiled channels and the contract document.</summary>
    [Fact] public void CapabilitiesDescribeOverlayTimelines() {using var json=JsonDocument.Parse(CompositionCliRunner.CapabilitiesJson());var timeline=json.RootElement.GetProperty("timeline");Assert.Equal("helengine.timeline.v1",timeline.GetProperty("format").GetString());Assert.Equal(["text","media","rect"],timeline.GetProperty("slot_kinds").EnumerateArray().Select(kind=>kind.GetString()));Assert.Equal(["opacity","reveal"],timeline.GetProperty("value_channels").EnumerateArray().Select(channel=>channel.GetString()));Assert.Contains(timeline.GetProperty("curves").EnumerateArray(),curve=>curve.GetString()=="ease_out_back.v1");Assert.Equal(0.18,timeline.GetProperty("default_text_size").GetDouble());Assert.EndsWith("#overlay-timelines",timeline.GetProperty("doc").GetString());}
    /// <summary>Unknown options and missing required input yield controlled nonzero exit codes.</summary>
    [Theory] [InlineData("unknown")] [InlineData("validate")] [InlineData("render")] public void InvalidInvocationReturnsFailure(string command) {Assert.Equal(1,VfxCliRunner.Run(["composition",command,"--unexpected","value"]));}
}
