<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\helengine.core\helengine.core.csproj" />
    <ProjectReference Include="..\helengine.vfx\helengine.vfx.csproj" />
    <ProjectReference Include="..\helengine.vfx.io\helengine.vfx.io.csproj" />
    <ProjectReference Include="..\helengine.vfx.directx11\helengine.vfx.directx11.csproj" />
    <ProjectReference Include="..\helengine.vfx.cli\helengine.vfx.cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\helengine.vfx.directx11\shaders\**\*.hlsl">
      <Link>shaders\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
