using helengine;

namespace helengine.editor.tests.testing {
    /// <summary>
    /// Provides a configurable mouse device for input-driven editor tests.
    /// </summary>
    public class TestMouse : Mouse {
        /// <summary>
        /// Client bounds used to simulate client-edge wrapping during tests.
        /// </summary>
        int2 ClientBounds;
        /// <summary>
        /// Tracks whether pointer wrapping is currently enabled for the active test interaction.
        /// </summary>
        bool PointerWrapEnabled;
        /// <summary>
        /// Delta offset generated by the most recent simulated pointer wrap.
        /// </summary>
        int2 PointerWrapDeltaOffset;

        /// <summary>
        /// Gets or sets the mouse state returned to the input manager.
        /// </summary>
        public MouseState State { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the owning window is currently foreground-active.
        /// </summary>
        public bool IsForegroundActive { get; set; } = true;
        /// <summary>
        /// Gets a value indicating whether simulated client-edge pointer wrapping is currently active.
        /// </summary>
        public bool IsPointerWrapEnabled {
            get { return PointerWrapEnabled; }
        }

        /// <summary>
        /// Configures the client bounds used when simulated pointer wrapping is enabled.
        /// </summary>
        /// <param name="clientBounds">Client width and height for the current test window.</param>
        public void SetClientBounds(int2 clientBounds) {
            ClientBounds = clientBounds;
        }

        /// <summary>
        /// Returns the configured mouse state for the current test frame.
        /// </summary>
        /// <returns>Mouse state supplied by the test.</returns>
        public override MouseState GetState() {
            MouseState currentState = State;
            PointerWrapDeltaOffset = new int2(0, 0);
            ApplyPointerWrap(ref currentState);

            if (!IsForegroundActive) {
                MouseState inactiveState = currentState;
                inactiveState.LeftButton = ButtonState.Released;
                inactiveState.MiddleButton = ButtonState.Released;
                inactiveState.RightButton = ButtonState.Released;
                inactiveState.XButton1 = ButtonState.Released;
                inactiveState.XButton2 = ButtonState.Released;
                return inactiveState;
            }

            return currentState;
        }

        /// <summary>
        /// Updates the stored cursor position in the configurable mouse state.
        /// </summary>
        /// <param name="x">Horizontal cursor position.</param>
        /// <param name="y">Vertical cursor position.</param>
        public override void SetPosition(int x, int y) {
            MouseState state = State;
            state.X = x;
            state.Y = y;
            State = state;
        }

        /// <summary>
        /// Enables or disables simulated client-edge pointer wrapping for the current test interaction.
        /// </summary>
        /// <param name="isEnabled">True when edge hits should wrap to the opposite interior edge.</param>
        public override void SetPointerWrapEnabled(bool isEnabled) {
            PointerWrapEnabled = isEnabled;
            if (!isEnabled) {
                PointerWrapDeltaOffset = new int2(0, 0);
            }
        }

        /// <summary>
        /// Returns and clears the wrap delta offset produced by the most recent simulated wrap.
        /// </summary>
        /// <returns>Offset used to preserve continuous deltas across a teleport.</returns>
        public override int2 ConsumePointerWrapDeltaOffset() {
            int2 pointerWrapDeltaOffset = PointerWrapDeltaOffset;
            PointerWrapDeltaOffset = new int2(0, 0);
            return pointerWrapDeltaOffset;
        }

        /// <summary>
        /// Applies client-edge wrapping to the simulated mouse state when wrapping is active.
        /// </summary>
        /// <param name="currentState">Mouse state that may be wrapped.</param>
        void ApplyPointerWrap(ref MouseState currentState) {
            if (!PointerWrapEnabled || ClientBounds.X <= 1 || ClientBounds.Y <= 1) {
                return;
            }

            int2 pointerWrapDeltaOffset = new int2(0, 0);

            if (currentState.X <= 0) {
                currentState.X = ClientBounds.X - 2;
                pointerWrapDeltaOffset.X = ClientBounds.X - 2;
            } else if (currentState.X >= ClientBounds.X - 1) {
                currentState.X = 1;
                pointerWrapDeltaOffset.X = ClientBounds.X - 2;
            }

            if (currentState.Y <= 0) {
                currentState.Y = ClientBounds.Y - 2;
                pointerWrapDeltaOffset.Y = ClientBounds.Y - 2;
            } else if (currentState.Y >= ClientBounds.Y - 1) {
                currentState.Y = 1;
                pointerWrapDeltaOffset.Y = ClientBounds.Y - 2;
            }

            if (currentState.X == ClientBounds.X - 2 && State.X <= 0) {
                pointerWrapDeltaOffset.X *= -1;
            }

            if (currentState.Y == ClientBounds.Y - 2 && State.Y <= 0) {
                pointerWrapDeltaOffset.Y *= -1;
            }

            PointerWrapDeltaOffset = pointerWrapDeltaOffset;
            State = currentState;
        }
    }
}
