namespace helengine.editor {
    /// <summary>
    /// Resolves file-system model source files into runtime models by importing or loading the processed cached model asset.
    /// </summary>
    public class EditorFileSystemModelResolver {
        /// <summary>
        /// Asset import manager that owns model import and cache reuse.
        /// </summary>
        readonly AssetImportManager AssetImportManager;

        /// <summary>
        /// Initializes a new resolver for one project asset import manager.
        /// </summary>
        /// <param name="assetImportManager">Asset import manager that can load processed model assets for source files.</param>
        public EditorFileSystemModelResolver(AssetImportManager assetImportManager) {
            if (assetImportManager == null) {
                throw new ArgumentNullException(nameof(assetImportManager));
            }

            AssetImportManager = assetImportManager;
        }

        /// <summary>
        /// Resolves one source model file into a runtime model using the processed cache generated by the asset import pipeline.
        /// </summary>
        /// <param name="sourcePath">Absolute path to the source model file under the project assets folder.</param>
        /// <returns>Runtime model built from the processed model asset.</returns>
        public RuntimeModel ResolveRuntimeModel(string sourcePath) {
            ModelAsset modelAsset = ResolveModelAsset(sourcePath);
            RuntimeModel runtimeModel = Core.Instance.RenderManager3D.BuildModelFromRaw(modelAsset);
            if (runtimeModel == null) {
                throw new InvalidOperationException($"Model importer did not return a runtime model for '{sourcePath}'.");
            }

            if (!string.IsNullOrWhiteSpace(modelAsset.Id)) {
                runtimeModel.SetId(modelAsset.Id);
            }

            return runtimeModel;
        }

        /// <summary>
        /// Resolves one source model file into the processed model asset generated by the asset import pipeline.
        /// </summary>
        /// <param name="sourcePath">Absolute path to the source model file under the project assets folder.</param>
        /// <returns>Processed model asset loaded from cache or freshly imported from the source file.</returns>
        public ModelAsset ResolveModelAsset(string sourcePath) {
            if (string.IsNullOrWhiteSpace(sourcePath)) {
                throw new ArgumentException("Source path must be provided.", nameof(sourcePath));
            }

            if (!AssetImportManager.TryLoadModelAsset(sourcePath, out ModelAsset modelAsset) || modelAsset == null) {
                throw new InvalidOperationException($"Unable to load processed model asset for '{sourcePath}'.");
            }

            return modelAsset;
        }
    }
}
