using System.Security.Cryptography;
using System.Text;
using helengine.editor;

namespace helengine.current_test_project_scene_generator {
    /// <summary>
    /// Builds the committed test-project rendering fixtures with current scene payloads and the public asset writer.
    /// </summary>
    public sealed class RenderingSceneFixtureGenerator {
        static readonly string[] SceneFileNamesValue = new[] {
            "depth-prepass.helen",
            "directional-shadow-lab.helen",
            "directional-shadow-plaza.helen",
            "material-inputs.helen",
            "opaque-basics.helen",
            "point-shadow-lab.helen",
            "point-shadow.helen",
            "ps2_basis_light_test.helen",
            "spot-shadow-lab.helen",
            "transparency-order.helen"
        };

        static readonly (string Name, string BaseColor)[] Ps2BasisMaterialDefinitions = new[] {
            ("Center", "#F0F0FFFF"),
            ("Corner", "#FFD040FF"),
            ("Ground", "#202838FF"),
            ("MinusX", "#C040FFFF"),
            ("MinusZ", "#4080FFFF"),
            ("PlusX", "#FF4040FF"),
            ("PlusZ", "#40D060FF")
        };

        const string SceneRootRelativePath = "Scenes/rendering";
        const string MaterialRootRelativePath = "Materials/rendering";
        const string BootstrapSceneRelativePath = "Scenes/Bootstrap.helen";
        const string CameraTypeId = "helengine.CameraComponent";
        const string MeshTypeId = "helengine.MeshComponent";
        const string PointLightTypeId = "helengine.PointLightComponent";
        const string SpotLightTypeId = "helengine.SpotLightComponent";
        const string DirectionalLightTypeId = "helengine.DirectionalLightComponent";
        const string CameraOrbitTypeId = "gameplay.rendering.DirectionalShadowCameraOrbitComponent, gameplay";
        const string OrbitTypeId = "gameplay.rendering.DirectionalShadowOrbitComponent, gameplay";
        const string SunSweepTypeId = "gameplay.rendering.DirectionalShadowSunSweepComponent, gameplay";
        const string TowerSpinTypeId = "gameplay.rendering.DirectionalShadowTowerSpinComponent, gameplay";
        const ushort SceneObjectsLayerMask = 0b0100000000000000;

        readonly GeneratedAssetWriteService AssetWriter = new GeneratedAssetWriteService();
        readonly GeneratedMaterialAssetWriteService MaterialWriter = new GeneratedMaterialAssetWriteService();
        readonly GeneratedSceneComponentAuthoringService ComponentAuthoringService = new GeneratedSceneComponentAuthoringService();

        /// <summary>
        /// Gets the exact committed rendering scene catalog generated by this maintenance tool.
        /// </summary>
        public static IReadOnlyList<string> SceneFileNames => SceneFileNamesValue;

        /// <summary>
        /// Generates every stale rendering fixture in the test project.
        /// </summary>
        /// <param name="projectRootPath">Project root that owns the test-project assets folder.</param>
        public void Generate(string projectRootPath) {
            if (string.IsNullOrWhiteSpace(projectRootPath)) {
                throw new ArgumentException("Project root path must be provided.", nameof(projectRootPath));
            }

            string root = Path.GetFullPath(projectRootPath);
            string sceneRoot = Path.Combine(root, "assets", SceneRootRelativePath.Replace('/', Path.DirectorySeparatorChar));
            if (!Directory.Exists(Path.Combine(root, "assets"))) {
                throw new InvalidOperationException($"Assets root was not found: {root}");
            }

            WriteMaterialDependencies(root);
            WritePs2BasisMaterialDependencies(root);
            WriteBootstrapScene(root);
            SceneAssetReference cube = EngineSceneAssetReferenceFactory.CreateCubeModel();
            SceneAssetReference plane = EngineSceneAssetReferenceFactory.CreatePlaneModel();
            SceneAssetReference standard = EngineSceneAssetReferenceFactory.CreateStandardMaterial();
            SceneAssetReference transparent = FileReference(root, "Materials/rendering/TransparentStandard.helmat");
            SceneAssetReference doubleSided = FileReference(root, "Materials/rendering/DoubleSidedStandard.helmat");

            Write(root, "opaque-basics.helen", BuildScene("opaque-basics", Camera(new float3(0f, 2f, -12f)),
                Meshes("opaque", cube, standard, 4), new[] { cube, standard }));
            Write(root, "transparency-order.helen", BuildScene("transparency-order", Camera(new float3(0f, 1f, -12f)),
                Meshes("transparency", cube, transparent, 3), new[] { cube, transparent }));
            Write(root, "depth-prepass.helen", BuildScene("depth-prepass", Camera(new float3(0f, 2f, -12f), "camera", "Camera", null, DepthPrepassMode.Always),
                Meshes("depth", cube, standard, 4), new[] { cube, standard }));
            Write(root, "material-inputs.helen", BuildScene("material-inputs", Camera(new float3(0f, 2f, -12f)),
                new[] { Mesh("material-input", "MaterialInput", new float3(0f, 0f, 0f), new float3(3f, 3f, 3f), cube, standard) },
                new[] { cube, standard, doubleSided }));

            Write(root, "point-shadow.helen", BuildPointShadowScene(root, cube, plane, standard));
            Write(root, "point-shadow-lab.helen", BuildPointShadowLabScene(root, cube, standard));
            Write(root, "spot-shadow-lab.helen", BuildSpotShadowLabScene(root, cube, standard));
            Write(root, "directional-shadow-lab.helen", BuildDirectionalShadowLabScene(root, cube, standard));
            Write(root, "directional-shadow-plaza.helen", BuildDirectionalShadowPlazaScene(root, cube, plane, standard));
            Write(root, "ps2_basis_light_test.helen", BuildScene("ps2_basis_light_test", Camera(new float3(0f, 3f, -14f)),
                Meshes("ps2", cube, standard, 6), new[] { cube, standard }));
        }

        SceneAsset BuildPointShadowScene(string projectRootPath, SceneAssetReference cube, SceneAssetReference plane, SceneAssetReference standard) {
            return BuildScene("point-shadow", Camera(new float3(0f, 3f, -12f)), new[] {
                Mesh("point-floor", "PointShadowFloor", new float3(0f, -1f, 0f), new float3(12f, 1f, 12f), plane, standard),
                Mesh("point-caster", "PointShadowCaster", new float3(0f, 0f, 0f), new float3(2f, 2f, 2f), cube, standard),
                Mesh("point-receiver", "PointShadowReceiver", new float3(4f, 0f, 3f), new float3(1.5f, 3f, 1.5f), cube, standard),
                Light("point-light", "PointShadowLight", new float3(2f, 4f, -1f), PointLightTypeId, PointLightPayload(18f, 6f))
            }, new[] { plane, cube, standard });
        }

        SceneAsset BuildPointShadowLabScene(string projectRootPath, SceneAssetReference cube, SceneAssetReference standard) {
            List<SceneEntityAsset> entities = new List<SceneEntityAsset> {
                Camera(new float3(0f, 0f, -36f), "point-shadow-lab-camera", "PointShadowLabCamera"),
                Mesh("point-shadow-lab-floor", "PointShadowLabFloor", new float3(0f, -24f, 0f), new float3(48f, 2f, 48f), cube, standard),
                Mesh("point-shadow-lab-ceiling", "PointShadowLabCeiling", new float3(0f, 24f, 0f), new float3(48f, 2f, 48f), cube, standard),
                Mesh("point-shadow-lab-wall-positive-x", "PointShadowLabWallPositiveX", new float3(24f, 0f, 0f), new float3(2f, 48f, 48f), cube, standard),
                Mesh("point-shadow-lab-wall-negative-x", "PointShadowLabWallNegativeX", new float3(-24f, 0f, 0f), new float3(2f, 48f, 48f), cube, standard),
                Mesh("point-shadow-lab-wall-positive-z", "PointShadowLabWallPositiveZ", new float3(0f, 0f, 24f), new float3(48f, 48f, 2f), cube, standard),
                Mesh("point-shadow-lab-wall-negative-z", "PointShadowLabWallNegativeZ", new float3(0f, 0f, -24f), new float3(48f, 48f, 2f), cube, standard),
                Mesh("point-shadow-lab-caster", "PointShadowLabCaster", new float3(8f, 0f, 6f), new float3(6f, 6f, 6f), cube, standard),
                Light("point-shadow-lab-light", "PointShadowLabLight", float3.Zero, PointLightTypeId, PointLightPayload(56f, 8f))
            };
            AddMarkers(entities, "point-shadow-lab-marker", cube, standard, 18f, 8f, 4f);
            return BuildScene("point-shadow-lab", entities.ToArray(), new[] { cube, standard });
        }

        SceneAsset BuildSpotShadowLabScene(string projectRootPath, SceneAssetReference cube, SceneAssetReference standard) {
            List<SceneEntityAsset> entities = new List<SceneEntityAsset> {
                Camera(new float3(0f, 0f, -28f), "spot-shadow-lab-camera", "SpotShadowLabCamera"),
                Mesh("spot-floor", "SpotShadowLabFloor", new float3(0f, -16f, 0f), new float3(32f, 2f, 32f), cube, standard),
                Mesh("spot-ceiling", "SpotShadowLabCeiling", new float3(0f, 16f, 0f), new float3(32f, 2f, 32f), cube, standard),
                Mesh("spot-wall-positive-x", "SpotShadowLabWallPositiveX", new float3(16f, 0f, 0f), new float3(2f, 32f, 32f), cube, standard),
                Mesh("spot-wall-negative-x", "SpotShadowLabWallNegativeX", new float3(-16f, 0f, 0f), new float3(2f, 32f, 32f), cube, standard),
                Mesh("spot-wall-positive-z", "SpotShadowLabWallPositiveZ", new float3(0f, 0f, 16f), new float3(32f, 32f, 2f), cube, standard),
                Mesh("spot-wall-negative-z", "SpotShadowLabWallNegativeZ", new float3(0f, 0f, -16f), new float3(32f, 32f, 2f), cube, standard),
                Mesh("spot-caster-primary", "SpotShadowLabCasterPrimary", new float3(4f, -8f, 6f), new float3(4f, 8f, 4f), cube, standard),
                Mesh("spot-caster-secondary", "SpotShadowLabCasterSecondary", new float3(-6f, -10f, 2f), new float3(3f, 4f, 3f), cube, standard),
                Light("spot-light", "SpotShadowLabLight", new float3(-4f, 10f, -8f), SpotLightTypeId, SpotLightPayload(30f, 28f, 40f, 8f))
            };
            AddMarkers(entities, "spot-marker", cube, standard, 12f, 8f, 3f, 4);
            return BuildScene("spot-shadow-lab", entities.ToArray(), new[] { cube, standard });
        }

        SceneAsset BuildDirectionalShadowLabScene(string projectRootPath, SceneAssetReference cube, SceneAssetReference standard) {
            List<SceneEntityAsset> entities = new List<SceneEntityAsset> {
                Camera(new float3(-12f, 10f, -24f), "directional-shadow-lab-camera", "DirectionalShadowLabCamera"),
                Mesh("directional-floor", "DirectionalShadowLabFloor", new float3(0f, -1f, 0f), new float3(48f, 1f, 48f), cube, standard),
                Mesh("directional-caster-left", "DirectionalShadowLabCasterLeft", new float3(-10f, 2f, -4f), new float3(4f, 4f, 4f), cube, standard),
                Mesh("directional-caster-center", "DirectionalShadowLabCasterCenter", new float3(0f, 4f, 0f), new float3(4f, 8f, 4f), cube, standard),
                Mesh("directional-caster-right", "DirectionalShadowLabCasterRight", new float3(10f, 3f, 6f), new float3(4f, 6f, 4f), cube, standard),
                Mesh("directional-column-front", "DirectionalShadowLabColumnFront", new float3(-4f, 6f, 14f), new float3(3f, 12f, 3f), cube, standard),
                Mesh("directional-column-back", "DirectionalShadowLabColumnBack", new float3(12f, 5f, -12f), new float3(3f, 10f, 3f), cube, standard),
                Mesh("directional-marker-left", "DirectionalShadowLabGroundMarkerLeft", new float3(-18f, 0.5f, 12f), new float3(2f, 1f, 2f), cube, standard),
                Mesh("directional-marker-center", "DirectionalShadowLabGroundMarkerCenter", new float3(-10f, 0.5f, 12f), new float3(2f, 1f, 2f), cube, standard),
                Mesh("directional-marker-right", "DirectionalShadowLabGroundMarkerRight", new float3(-10f, 0.5f, 20f), new float3(2f, 1f, 2f), cube, standard),
                Light("directional-light", "DirectionalShadowLabLight", new float3(0f, 12f, 0f), DirectionalLightTypeId, DirectionalLightPayload(2.8f, 60f))
            };
            return BuildScene("directional-shadow-lab", entities.ToArray(), new[] { cube, standard });
        }

        SceneAsset BuildDirectionalShadowPlazaScene(string projectRootPath, SceneAssetReference cube, SceneAssetReference plane, SceneAssetReference standard) {
            List<SceneEntityAsset> entities = new List<SceneEntityAsset> {
                Camera(new float3(0f, 10f, -26f), "directional-shadow-plaza-camera", "DirectionalShadowPlazaCamera", CameraOrbitTypeId),
                Light("directional-shadow-plaza-sun", "DirectionalShadowPlazaSun", new float3(0f, 18f, 0f), DirectionalLightTypeId, DirectionalLightPayload(2.8f, 60f), SunSweepTypeId),
                Mesh("directional-shadow-plaza-ground", "DirectionalShadowPlazaGround", new float3(0f, -0.5f, 0f), new float3(42f, 1f, 42f), plane, standard),
                Mesh("directional-shadow-plaza-tower-left", "DirectionalShadowPlazaTowerLeft", new float3(-10f, 4f, -6f), new float3(3f, 8f, 3f), cube, standard, TowerSpinTypeId),
                Mesh("directional-shadow-plaza-tower-center", "DirectionalShadowPlazaTowerCenter", new float3(0f, 5f, 0f), new float3(4f, 10f, 4f), cube, standard, TowerSpinTypeId),
                Mesh("directional-shadow-plaza-tower-right", "DirectionalShadowPlazaTowerRight", new float3(11f, 3.5f, 7f), new float3(3f, 7f, 3f), cube, standard, TowerSpinTypeId),
                Mesh("directional-shadow-plaza-hero", "DirectionalShadowPlazaHero", new float3(0f, 3f, 12f), new float3(3f, 6f, 3f), cube, standard, OrbitTypeId),
                Mesh("directional-shadow-plaza-receiver-a", "DirectionalShadowPlazaReceiverA", new float3(-18f, 0.5f, 16f), new float3(2f, 1f, 2f), cube, standard),
                Mesh("directional-shadow-plaza-receiver-b", "DirectionalShadowPlazaReceiverB", new float3(-8f, 1.5f, 19f), new float3(3f, 3f, 3f), cube, standard),
                Mesh("directional-shadow-plaza-receiver-c", "DirectionalShadowPlazaReceiverC", new float3(16f, 1f, -14f), new float3(2f, 2f, 5f), cube, standard),
                Mesh("directional-shadow-plaza-receiver-d", "DirectionalShadowPlazaReceiverD", new float3(17f, 2f, 12f), new float3(4f, 4f, 2f), cube, standard)
            };
            return BuildScene("directional-shadow-plaza", entities.ToArray(), new[] { plane, cube, standard });
        }

        SceneAsset BuildScene(string id, SceneEntityAsset camera, SceneEntityAsset[] meshes, SceneAssetReference[] references) {
            SceneEntityAsset[] entities = new SceneEntityAsset[meshes.Length + 1];
            entities[0] = camera;
            Array.Copy(meshes, 0, entities, 1, meshes.Length);
            return BuildScene(id, entities, references);
        }

        SceneAsset BuildScene(string id, SceneEntityAsset[] entities, SceneAssetReference[] references) {
            return new SceneAsset {
                Id = SceneRootRelativePath + "/" + id + SceneAsset.FileExtension,
                AssetReferences = references,
                RootEntities = entities,
                SceneSettings = new SceneSettingsAsset()
            };
        }

        SceneEntityAsset[] Meshes(string prefix, SceneAssetReference model, SceneAssetReference material, int count) {
            SceneEntityAsset[] meshes = new SceneEntityAsset[count];
            for (int index = 0; index < count; index++) {
                meshes[index] = Mesh(prefix + "-mesh-" + index, prefix + "Mesh" + index, new float3(index * 3f - 3f, 0f, index), new float3(2f, 2f, 2f), model, material);
            }
            return meshes;
        }

        void AddMarkers(List<SceneEntityAsset> entities, string prefix, SceneAssetReference model, SceneAssetReference material, float distance, float offset, float scale, int count = 18) {
            for (int index = 0; index < count; index++) {
                float angle = (float)(index * Math.PI * 2d / count);
                entities.Add(Mesh(prefix + "-" + index, prefix + "" + index, new float3((float)Math.Cos(angle) * distance, index % 3 * offset - offset, (float)Math.Sin(angle) * distance), new float3(scale, scale, scale), model, material));
            }
        }

        SceneEntityAsset Camera(float3 position, string id = "camera", string name = "Camera", string scriptTypeId = null, DepthPrepassMode depthPrepassMode = DepthPrepassMode.Auto) {
            List<SceneComponentAssetRecord> records = new List<SceneComponentAssetRecord> { Component(CameraTypeId, CameraPayload(depthPrepassMode)) };
            if (!string.IsNullOrWhiteSpace(scriptTypeId)) {
                records.Add(Component(scriptTypeId, ScriptPayload()));
            }
            return Entity(id, name, position, float3.One, records.ToArray());
        }

        SceneEntityAsset Mesh(string id, string name, float3 position, float3 scale, SceneAssetReference model, SceneAssetReference material, string scriptTypeId = null) {
            List<SceneComponentAssetRecord> records = new List<SceneComponentAssetRecord> { Component(MeshTypeId, MeshPayload(model, material)) };
            if (!string.IsNullOrWhiteSpace(scriptTypeId)) {
                records.Add(Component(scriptTypeId, ScriptPayload()));
            }
            return Entity(id, name, position, scale, records.ToArray());
        }

        SceneEntityAsset Light(string id, string name, float3 position, string typeId, byte[] payload, string scriptTypeId = null) {
            List<SceneComponentAssetRecord> records = new List<SceneComponentAssetRecord> { Component(typeId, payload) };
            if (!string.IsNullOrWhiteSpace(scriptTypeId)) {
                records.Add(Component(scriptTypeId, ScriptPayload()));
            }
            return Entity(id, name, position, float3.One, records.ToArray());
        }

        SceneEntityAsset Entity(string id, string name, float3 position, float3 scale, SceneComponentAssetRecord[] components) {
            return new SceneEntityAsset {
                Id = StableEntityId(id),
                Name = name,
                LocalPosition = position,
                LocalScale = scale,
                LocalOrientation = float4.Identity,
                Components = components,
                Children = Array.Empty<SceneEntityAsset>()
            };
        }

        static uint StableEntityId(string value) {
            if (string.IsNullOrWhiteSpace(value)) {
                throw new ArgumentException("Entity id must be provided.", nameof(value));
            }

            uint hash = 2166136261u;
            for (int index = 0; index < value.Length; index++) {
                hash ^= value[index];
                hash *= 16777619u;
            }

            return hash == 0 ? 1u : hash;
        }

        SceneComponentAssetRecord Component(string typeId, byte[] payload) {
            return new SceneComponentAssetRecord {
                ComponentTypeId = typeId,
                ComponentIndex = 0,
                Payload = payload
            };
        }

        byte[] CameraPayload(DepthPrepassMode depthPrepassMode) {
            CameraComponent camera = new CameraComponent {
                CameraDrawOrder = 0,
                LayerMask = SceneObjectsLayerMask,
                Viewport = new float4(0f, 0f, 1280f, 720f),
                NearPlaneDistance = 0.1f,
                FarPlaneDistance = 1000f,
                ClearSettings = new CameraClearSettings(true, new float4(0.06f, 0.06f, 0.09f, 1f), true, 1f, false, 0),
                RenderSettings = new CameraRenderSettings {
                DepthPrepassMode = depthPrepassMode,
                ShadowDistance = 60f,
                PostProcessTier = PostProcessTier.Disabled
                }
            };
            return ComponentAuthoringService.CreateCameraPayload(camera);
        }

        byte[] MeshPayload(SceneAssetReference model, SceneAssetReference material) {
            return ComponentAuthoringService.CreateMeshPayload(model, material);
        }

        byte[] PointLightPayload(float range, float intensity) {
            return LightPayload(new PointLightComponent { Range = range, Intensity = intensity, Color = new float4(1f, 0.92f, 0.78f, 1f), ShadowsEnabled = true, ShadowMapMode = ShadowMapMode.Forced, ShadowStrength = 1f });
        }

        byte[] SpotLightPayload(float range, float innerCone, float outerCone, float intensity) {
            return LightPayload(new SpotLightComponent { Range = range, InnerConeAngleDegrees = innerCone, OuterConeAngleDegrees = outerCone, Intensity = intensity, Color = new float4(1f, 0.93f, 0.82f, 1f), ShadowsEnabled = true, ShadowMapMode = ShadowMapMode.Forced, ShadowStrength = 1f });
        }

        byte[] DirectionalLightPayload(float intensity, float shadowDistance) {
            return LightPayload(new DirectionalLightComponent { ShadowDistance = shadowDistance, Intensity = intensity, Color = new float4(1f, 0.96f, 0.90f, 1f), ShadowsEnabled = true, ShadowMapMode = ShadowMapMode.Forced, ShadowStrength = 1f });
        }

        byte[] LightPayload(Component component) {
            return ComponentAuthoringService.CreateLightPayload(component);
        }

        byte[] ScriptPayload() {
            return ComponentAuthoringService.CreateEmptyScriptPayload();
        }

        void Write(string projectRootPath, string fileName, SceneAsset scene) {
            scene.AuthoringAssetId = CreateStableAuthoringAssetId(SceneRootRelativePath + "/" + fileName);
            scene.FormerAuthoringAssetIds = Array.Empty<string>();
            AssetWriter.WriteAsset(projectRootPath, SceneRootRelativePath + "/" + fileName, scene);
        }

        /// <summary>
        /// Writes the current common-settings documents referenced by the rendering scene catalog.
        /// </summary>
        /// <param name="projectRootPath">Project root that owns the test-project assets.</param>
        void WriteMaterialDependencies(string projectRootPath) {
            MaterialWriter.WriteMaterial(
                projectRootPath,
                MaterialRootRelativePath + "/TransparentStandard.helmat",
                CreateMaterialDefinition(
                    "Materials/rendering/TransparentStandard",
                    "alpha-blend",
                    false,
                    "transparent-standard"));
            MaterialWriter.WriteMaterial(
                projectRootPath,
                MaterialRootRelativePath + "/DoubleSidedStandard.helmat",
                CreateMaterialDefinition(
                    "Materials/rendering/DoubleSidedStandard",
                    "opaque",
                    true,
                    "double-sided-standard"));
        }

        /// <summary>
        /// Rewrites the stale PS2 basis material family and its Windows/PS2 settings through the current material writer.
        /// </summary>
        /// <param name="projectRootPath">Project root that owns the test-project assets.</param>
        void WritePs2BasisMaterialDependencies(string projectRootPath) {
            for (int index = 0; index < Ps2BasisMaterialDefinitions.Length; index++) {
                (string name, string baseColor) = Ps2BasisMaterialDefinitions[index];
                string materialRelativePath = MaterialRootRelativePath + "/ps2_basis_light_test/" + name + ".hasset";
                string materialId = MaterialRootRelativePath + ".ps2_basis_light_test." + name;
                GeneratedMaterialAssetDefinition definition = new GeneratedMaterialAssetDefinition {
                    MaterialAsset = new ShaderMaterialAsset {
                        Id = materialId,
                        AuthoringAssetId = CreateStableAuthoringAssetId(materialRelativePath),
                        FormerAuthoringAssetIds = Array.Empty<string>(),
                        RenderState = new MaterialRenderState {
                            BlendMode = MaterialBlendMode.Opaque,
                            CullMode = MaterialCullMode.Back,
                            DepthTestEnabled = true,
                            DepthWriteEnabled = true
                        },
                        CastsShadows = true,
                        ReceivesShadows = true
                    }
                };

                GeneratedMaterialPlatformDefinition windows = definition.GetOrCreatePlatform("windows");
                windows.SchemaId = "standard-shader";
                windows.SetFieldValue("use-custom-shader", "false");
                windows.SetFieldValue("texture-id", string.Empty);
                windows.SetFieldValue("casts-shadow", "true");
                windows.SetFieldValue("receives-shadow", "true");
                windows.SetFieldValue("base-color", baseColor);

                GeneratedMaterialPlatformDefinition ps2 = definition.GetOrCreatePlatform("ps2");
                ps2.SchemaId = "ps2-simple-lit-textured";
                ps2.SetFieldValue("alpha-mode", "opaque");
                ps2.SetFieldValue("double-sided", "false");
                ps2.SetFieldValue("cast-shadows", "true");
                ps2.SetFieldValue("vertex-color-mode", "ignore");
                ps2.SetFieldValue("base-color", baseColor);

                MaterialWriter.WriteMaterial(projectRootPath, materialRelativePath, definition);
            }
        }

        /// <summary>
        /// Rewrites the project bootstrap scene through the current native asset writer.
        /// </summary>
        /// <param name="projectRootPath">Project root that owns the test-project assets.</param>
        void WriteBootstrapScene(string projectRootPath) {
            SceneAsset bootstrapScene = new SceneAsset {
                Id = BootstrapSceneRelativePath,
                AuthoringAssetId = CreateStableAuthoringAssetId(BootstrapSceneRelativePath),
                FormerAuthoringAssetIds = Array.Empty<string>(),
                AssetReferences = Array.Empty<SceneAssetReference>(),
                RootEntities = Array.Empty<SceneEntityAsset>(),
                SceneSettings = new SceneSettingsAsset()
            };
            AssetWriter.WriteAsset(projectRootPath, BootstrapSceneRelativePath, bootstrapScene);
        }

        /// <summary>
        /// Creates one current standard-shader material definition for the rendering catalog.
        /// </summary>
        /// <param name="materialId">Stable material importer id.</param>
        /// <param name="alphaMode">Standard shader alpha-mode value.</param>
        /// <param name="doubleSided">Whether back-face culling is disabled.</param>
        /// <param name="identitySeed">Stable identity seed for the authored settings document.</param>
        /// <returns>Current generated material definition.</returns>
        static GeneratedMaterialAssetDefinition CreateMaterialDefinition(
            string materialId,
            string alphaMode,
            bool doubleSided,
            string identitySeed) {
            GeneratedMaterialAssetDefinition definition = new GeneratedMaterialAssetDefinition {
                MaterialAsset = new ShaderMaterialAsset {
                    Id = materialId,
                    AuthoringAssetId = CreateStableAuthoringAssetId(identitySeed),
                    FormerAuthoringAssetIds = Array.Empty<string>(),
                    RenderState = new MaterialRenderState {
                        BlendMode = string.Equals(alphaMode, "alpha-blend", StringComparison.Ordinal)
                            ? MaterialBlendMode.AlphaBlend
                            : MaterialBlendMode.Opaque,
                        CullMode = doubleSided ? MaterialCullMode.None : MaterialCullMode.Back,
                        DepthTestEnabled = true,
                        DepthWriteEnabled = !string.Equals(alphaMode, "alpha-blend", StringComparison.Ordinal)
                    },
                    CastsShadows = true,
                    ReceivesShadows = true
                }
            };
            GeneratedMaterialPlatformDefinition platform = definition.GetOrCreatePlatform("windows");
            platform.SchemaId = "standard-shader";
            platform.SetFieldValue("use-custom-shader", "false");
            platform.SetFieldValue("shader-asset-id", "ForwardStandardShader");
            platform.SetFieldValue("alpha-mode", alphaMode);
            platform.SetFieldValue("double-sided", doubleSided ? "true" : "false");
            platform.SetFieldValue("casts-shadow", "true");
            platform.SetFieldValue("receives-shadow", "true");
            platform.SetFieldValue("base-color", "#FFFFFFFF");
            return definition;
        }

        /// <summary>
        /// Derives one stable lower-case hexadecimal authoring identity from a committed logical path.
        /// </summary>
        /// <param name="logicalPath">Stable logical path used as the identity seed.</param>
        /// <returns>32-character lower-case hexadecimal authoring identity.</returns>
        static string CreateStableAuthoringAssetId(string logicalPath) {
            if (string.IsNullOrWhiteSpace(logicalPath)) {
                throw new ArgumentException("Logical path must be provided.", nameof(logicalPath));
            }

            byte[] digest = SHA256.HashData(Encoding.UTF8.GetBytes("helengine.current-test-project-rendering|" + logicalPath));
            return Convert.ToHexString(digest, 0, 16).ToLowerInvariant();
        }

        static SceneAssetReference FileReference(string projectRootPath, string relativePath) {
            string fullPath = Path.Combine(projectRootPath, "assets", relativePath.Replace('/', Path.DirectorySeparatorChar));
            byte[] content = File.ReadAllBytes(fullPath);
            byte[] digest = System.Security.Cryptography.SHA256.HashData(content);
            string hex = Convert.ToHexString(digest).ToLowerInvariant();
            return SceneAssetReferenceFactory.CreateFileSystemReference(hex.Substring(0, 32), relativePath, "sha256:" + hex);
        }
    }
}
