using System.Text.Json;

namespace helshader {
    /// <summary>
    /// Reads reflection JSON files generated by shader compilation tools.
    /// </summary>
    public class ShaderReflectionReader {
        /// <summary>
        /// Loads a reflection entry from the specified JSON path.
        /// </summary>
        /// <param name="path">Absolute path to the reflection JSON file.</param>
        /// <returns>Parsed reflection entry.</returns>
        public ShaderReflectionEntry Load(string path) {
            if (string.IsNullOrWhiteSpace(path)) {
                throw new ArgumentException("Reflection path must be provided.", nameof(path));
            }

            if (!File.Exists(path)) {
                throw new FileNotFoundException("Reflection file was not found.", path);
            }

            string json = File.ReadAllText(path);
            JsonSerializerOptions options = new JsonSerializerOptions {
                PropertyNameCaseInsensitive = true,
                ReadCommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true
            };

            ShaderReflectionEntry entry = JsonSerializer.Deserialize<ShaderReflectionEntry>(json, options);
            if (entry == null) {
                throw new InvalidOperationException("Reflection file could not be parsed.");
            }

            return entry;
        }
    }
}
