namespace helengine {
    /// <summary>Lists every valid GX2SurfaceFormat declaration in the pinned native SDK; INVALID is rejected.</summary>
    public static class WiiUNativeTextureFormatCatalog {
        /// <summary>Retains process-lifetime descriptions for the exact SDK format words.</summary>
        static readonly WiiUNativeTextureFormatDefinition[] NativeFormats = new WiiUNativeTextureFormatDefinition[] {
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R4_G4", 0x02U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R4_G4_B4_A4", 0x0bU),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R8", 0x01U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R8_G8", 0x07U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R8_G8_B8_A8", 0x01aU),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R16", 0x05U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R16_G16", 0x0fU),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R16_G16_B16_A16", 0x01fU),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R5_G6_B5", 0x08U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R5_G5_B5_A1", 0x0aU),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_A1_B5_G5_R5", 0x0cU),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R24_X8", 0x011U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_A2_B10_G10_R10", 0x01bU),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_R10_G10_B10_A2", 0x019U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_BC1", 0x031U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_BC2", 0x032U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_BC3", 0x033U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_BC4", 0x034U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_BC5", 0x035U),
            new WiiUNativeTextureFormatDefinition("WiiU.UNORM_NV12", 0x081U),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R8", 0x101U),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R8_G8", 0x107U),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R8_G8_B8_A8", 0x11aU),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R16", 0x105U),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R16_G16", 0x10fU),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R16_G16_B16_A16", 0x11fU),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R32", 0x10dU),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R32_G32", 0x11dU),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R32_G32_B32_A32", 0x122U),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_A2_B10_G10_R10", 0x11bU),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_R10_G10_B10_A2", 0x119U),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_X24_G8", 0x111U),
            new WiiUNativeTextureFormatDefinition("WiiU.UINT_G8_X24", 0x11cU),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_R8", 0x201U),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_R8_G8", 0x207U),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_R8_G8_B8_A8", 0x21aU),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_R16", 0x205U),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_R16_G16", 0x20fU),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_R16_G16_B16_A16", 0x21fU),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_R10_G10_B10_A2", 0x219U),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_BC4", 0x234U),
            new WiiUNativeTextureFormatDefinition("WiiU.SNORM_BC5", 0x235U),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R8", 0x301U),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R8_G8", 0x307U),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R8_G8_B8_A8", 0x31aU),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R16", 0x305U),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R16_G16", 0x30fU),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R16_G16_B16_A16", 0x31fU),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R32", 0x30dU),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R32_G32", 0x31dU),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R32_G32_B32_A32", 0x322U),
            new WiiUNativeTextureFormatDefinition("WiiU.SINT_R10_G10_B10_A2", 0x319U),
            new WiiUNativeTextureFormatDefinition("WiiU.SRGB_R8_G8_B8_A8", 0x41aU),
            new WiiUNativeTextureFormatDefinition("WiiU.SRGB_BC1", 0x431U),
            new WiiUNativeTextureFormatDefinition("WiiU.SRGB_BC2", 0x432U),
            new WiiUNativeTextureFormatDefinition("WiiU.SRGB_BC3", 0x433U),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_R32", 0x80eU),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_R32_G32", 0x81eU),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_R32_G32_B32_A32", 0x823U),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_R16", 0x806U),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_R16_G16", 0x810U),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_R16_G16_B16_A16", 0x820U),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_R11_G11_B10", 0x816U),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_D24_S8", 0x811U),
            new WiiUNativeTextureFormatDefinition("WiiU.FLOAT_X8_X24", 0x81cU),
        };
        /// <summary>Gets borrowed native SDK descriptions, including explicit raw-only shader formats.</summary>
        [NativeBorrowedReturn] public static WiiUNativeTextureFormatDefinition[] Formats { get { return NativeFormats; } }
        /// <summary>Finds a borrowed format by its stable exact SDK identifier.</summary>
        public static bool TryGetFormat(string id, out WiiUNativeTextureFormatDefinition format) { for (int index = 0; index < NativeFormats.Length; index++) if (NativeFormats[index].Id == id) { format = NativeFormats[index]; return true; } format = null; return false; }
        /// <summary>Finds a borrowed description by an exact declared GX2SurfaceFormat word.</summary>
        public static bool TryGetHardwareFormat(uint hardwareFormat, out WiiUNativeTextureFormatDefinition format) { for (int index = 0; index < NativeFormats.Length; index++) if (NativeFormats[index].HardwareFormat == hardwareFormat) { format = NativeFormats[index]; return true; } format = null; return false; }
    }
}
